import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>Главная страница</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <main>Главная страница</main>
        </>
    );
}
