import Head from "next/head";
import Slider from "@/components/main/Slider/Slider";

export default function Home() {
    return (
        <>
            <Head>
                <title>План Б Недвижимость</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <div style={{ height: "2000px" }}>
                <Slider />
            </div>
        </>
    );
}
