import Head from "next/head";

export default function Home() {
    return (
        <>
            <Head>
                <title>План Б Недвижимость</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
            </Head>
            <div style={{ height: "2000px" }}></div>
        </>
    );
}
